# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w2iHJs5RhY4Bw2lbJ_Y3AwRyUNkyn9oy
"""

!pip install yfinance xgboost -q

import pandas as pd
import numpy as np
import yfinance as yf
import xgboost as xgb
import matplotlib.pyplot as plt

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

df = yf.download(
    "BTC-USD",
    start="2018-01-01",
    end="2025-01-01",
    auto_adjust=True
)

df.head()

if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

print(df.columns)

df['MA_7'] = df['Close'].rolling(7).mean()

df['MA_30'] = df['Close'].rolling(30).mean()

df['Daily_Return'] = df['Close'].pct_change()

delta = df['Close'].diff()

gain = delta.clip(lower=0)
loss = -delta.clip(upper=0)

avg_gain = gain.rolling(14).mean()
avg_loss = loss.rolling(14).mean()

rs = avg_gain / avg_loss

df['RSI_14'] = 100 - (100 / (1 + rs))

df.head()

print(df.isnull().sum())

df = df.dropna()

print(df.shape)

features = [
    'Open',
    'High',
    'Low',
    'Volume',
    'MA_7',
    'MA_30',
    'RSI_14',
    'Daily_Return'
]

X = df[features]
y = df['Close']

print(X.shape)
print(y.shape)

split = int(len(df) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

print("Train :", X_train.shape)
print("Test  :", X_test.shape)

model = xgb.XGBRegressor(
    n_estimators=500,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("RMSE :", rmse)
print("MAE  :", mae)
print("R2   :", r2)

plt.figure(figsize=(15,6))

plt.plot(y_test.values, label='Actual')

plt.plot(y_pred, label='Prediction')

plt.legend()

plt.title('Bitcoin Price Prediction Using XGBoost')

plt.show()

df.to_csv("bitcoin_xgboost_features.csv", index=True)

df.to_csv("bitcoin_xgboost_features.csv", index=True)
print("CSV berhasil disimpan")

df.head()

df.to_csv("bitcoin_xgboost_features.csv", index=True)

print("CSV berhasil disimpan")

df.to_csv("bitcoin_xgboost_features.csv", index=True)

print("CSV berhasil disimpan")

